# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(760, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.patientTypeList = QtWidgets.QListWidget(self.centralwidget)
        self.patientTypeList.setGeometry(QtCore.QRect(20, 30, 121, 111))
        self.patientTypeList.setObjectName("patientTypeList")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 10, 101, 16))
        self.label.setObjectName("label")
        self.patientNumberList = QtWidgets.QListWidget(self.centralwidget)
        self.patientNumberList.setGeometry(QtCore.QRect(150, 30, 121, 111))
        self.patientNumberList.setObjectName("patientNumberList")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(150, 10, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 150, 101, 16))
        self.label_3.setObjectName("label_3")
        self.sampleDateList = QtWidgets.QListWidget(self.centralwidget)
        self.sampleDateList.setGeometry(QtCore.QRect(20, 170, 121, 121))
        self.sampleDateList.setObjectName("sampleDateList")
        self.compartmentList = QtWidgets.QListWidget(self.centralwidget)
        self.compartmentList.setGeometry(QtCore.QRect(150, 170, 121, 121))
        self.compartmentList.setObjectName("compartmentList")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(150, 150, 101, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(360, 10, 101, 16))
        self.label_5.setObjectName("label_5")
        self.geneList = QtWidgets.QListWidget(self.centralwidget)
        self.geneList.setGeometry(QtCore.QRect(360, 30, 101, 261))
        self.geneList.setObjectName("geneList")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(570, 10, 141, 16))
        self.label_7.setObjectName("label_7")
        self.numSeqText = QtWidgets.QTextEdit(self.centralwidget)
        self.numSeqText.setGeometry(QtCore.QRect(570, 30, 161, 21))
        self.numSeqText.setObjectName("numSeqText")
        self.addCDSButton = QtWidgets.QPushButton(self.centralwidget)
        self.addCDSButton.setGeometry(QtCore.QRect(570, 100, 171, 32))
        self.addCDSButton.setObjectName("addCDSButton")
        self.addProteinsButton = QtWidgets.QPushButton(self.centralwidget)
        self.addProteinsButton.setGeometry(QtCore.QRect(570, 140, 171, 32))
        self.addProteinsButton.setObjectName("addProteinsButton")
        self.treeButton = QtWidgets.QPushButton(self.centralwidget)
        self.treeButton.setGeometry(QtCore.QRect(570, 220, 171, 32))
        self.treeButton.setObjectName("treeButton")
        self.alignButton = QtWidgets.QPushButton(self.centralwidget)
        self.alignButton.setGeometry(QtCore.QRect(570, 180, 171, 32))
        self.alignButton.setObjectName("alignButton")
        self.clearButton = QtWidgets.QPushButton(self.centralwidget)
        self.clearButton.setGeometry(QtCore.QRect(570, 260, 171, 32))
        self.clearButton.setObjectName("clearButton")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 310, 141, 16))
        self.label_6.setObjectName("label_6")
        self.selectedSequencesArea = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.selectedSequencesArea.setGeometry(QtCore.QRect(20, 330, 721, 211))
        self.selectedSequencesArea.setObjectName("selectedSequencesArea")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(570, 60, 121, 20))
        self.checkBox.setObjectName("checkBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 760, 24))
        self.menubar.setObjectName("menubar")
        self.menuNew_entry = QtWidgets.QMenu(self.menubar)
        self.menuNew_entry.setObjectName("menuNew_entry")
        self.menuNew_entry_2 = QtWidgets.QMenu(self.menuNew_entry)
        self.menuNew_entry_2.setObjectName("menuNew_entry_2")
        self.menuNew_sequence = QtWidgets.QMenu(self.menuNew_entry)
        self.menuNew_sequence.setObjectName("menuNew_sequence")
        self.menuSync = QtWidgets.QMenu(self.menubar)
        self.menuSync.setObjectName("menuSync")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuEdit = QtWidgets.QMenu(self.menubar)
        self.menuEdit.setObjectName("menuEdit")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionFrom_genome = QtWidgets.QAction(MainWindow)
        self.actionFrom_genome.setObjectName("actionFrom_genome")
        self.actionFrom_reads = QtWidgets.QAction(MainWindow)
        self.actionFrom_reads.setObjectName("actionFrom_reads")
        self.actionFrom_NCBI = QtWidgets.QAction(MainWindow)
        self.actionFrom_NCBI.setObjectName("actionFrom_NCBI")
        self.actionSave_alignment = QtWidgets.QAction(MainWindow)
        self.actionSave_alignment.setEnabled(False)
        self.actionSave_alignment.setObjectName("actionSave_alignment")
        self.actionSave_tree = QtWidgets.QAction(MainWindow)
        self.actionSave_tree.setEnabled(False)
        self.actionSave_tree.setObjectName("actionSave_tree")
        self.actionSave_sequences = QtWidgets.QAction(MainWindow)
        self.actionSave_sequences.setEnabled(False)
        self.actionSave_sequences.setObjectName("actionSave_sequences")
        self.actionQuit = QtWidgets.QAction(MainWindow)
        self.actionQuit.setObjectName("actionQuit")
        self.actionModify_entry = QtWidgets.QAction(MainWindow)
        self.actionModify_entry.setObjectName("actionModify_entry")
        self.actionAnnotated_from_reads_fastq = QtWidgets.QAction(MainWindow)
        self.actionAnnotated_from_reads_fastq.setObjectName("actionAnnotated_from_reads_fastq")
        self.actionFrom_genome_fasta = QtWidgets.QAction(MainWindow)
        self.actionFrom_genome_fasta.setObjectName("actionFrom_genome_fasta")
        self.actionFrom_NCBI_accessio_number = QtWidgets.QAction(MainWindow)
        self.actionFrom_NCBI_accessio_number.setObjectName("actionFrom_NCBI_accessio_number")
        self.actionBlank_entry = QtWidgets.QAction(MainWindow)
        self.actionBlank_entry.setObjectName("actionBlank_entry")
        self.actionTo_existing_entry = QtWidgets.QAction(MainWindow)
        self.actionTo_existing_entry.setObjectName("actionTo_existing_entry")
        self.actionProtein = QtWidgets.QAction(MainWindow)
        self.actionProtein.setObjectName("actionProtein")
        self.menuNew_entry_2.addAction(self.actionAnnotated_from_reads_fastq)
        self.menuNew_entry_2.addAction(self.actionFrom_genome_fasta)
        self.menuNew_entry_2.addAction(self.actionFrom_NCBI_accessio_number)
        self.menuNew_entry_2.addAction(self.actionBlank_entry)
        self.menuNew_sequence.addAction(self.actionTo_existing_entry)
        self.menuNew_sequence.addAction(self.actionProtein)
        self.menuNew_entry.addAction(self.menuNew_entry_2.menuAction())
        self.menuNew_entry.addAction(self.menuNew_sequence.menuAction())
        self.menuFile.addAction(self.actionSave_sequences)
        self.menuFile.addAction(self.actionSave_alignment)
        self.menuFile.addAction(self.actionSave_tree)
        self.menuFile.addAction(self.actionQuit)
        self.menuEdit.addAction(self.actionModify_entry)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuEdit.menuAction())
        self.menubar.addAction(self.menuNew_entry.menuAction())
        self.menubar.addAction(self.menuSync.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Patient type"))
        self.label_2.setText(_translate("MainWindow", "Patient number"))
        self.label_3.setText(_translate("MainWindow", "Sample date"))
        self.label_4.setText(_translate("MainWindow", "Compartment"))
        self.label_5.setText(_translate("MainWindow", "Gene"))
        self.label_7.setText(_translate("MainWindow", "Found sequences"))
        self.numSeqText.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">0</p></body></html>"))
        self.addCDSButton.setText(_translate("MainWindow", "Add CDS"))
        self.addProteinsButton.setText(_translate("MainWindow", "Add proteins"))
        self.treeButton.setText(_translate("MainWindow", "Tree"))
        self.alignButton.setText(_translate("MainWindow", "Align"))
        self.clearButton.setText(_translate("MainWindow", "Clear preview"))
        self.label_6.setText(_translate("MainWindow", "Preview"))
        self.checkBox.setText(_translate("MainWindow", "Include pseudo"))
        self.menuNew_entry.setTitle(_translate("MainWindow", "Insert"))
        self.menuNew_entry_2.setTitle(_translate("MainWindow", "New entry"))
        self.menuNew_sequence.setTitle(_translate("MainWindow", "New sequence"))
        self.menuSync.setTitle(_translate("MainWindow", "Sync"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.menuEdit.setTitle(_translate("MainWindow", "Edit"))
        self.actionFrom_genome.setText(_translate("MainWindow", "From genome (fasta)"))
        self.actionFrom_reads.setText(_translate("MainWindow", "From reads (fastq)"))
        self.actionFrom_NCBI.setText(_translate("MainWindow", "From NCBI accession no."))
        self.actionSave_alignment.setText(_translate("MainWindow", "Save alignment (fasta)"))
        self.actionSave_tree.setText(_translate("MainWindow", "Save tree"))
        self.actionSave_sequences.setText(_translate("MainWindow", "Save sequences (fasta)"))
        self.actionQuit.setText(_translate("MainWindow", "Quit"))
        self.actionModify_entry.setText(_translate("MainWindow", "Modify entry"))
        self.actionAnnotated_from_reads_fastq.setText(_translate("MainWindow", "From reads (fastq)"))
        self.actionFrom_genome_fasta.setText(_translate("MainWindow", "From genome (fasta)"))
        self.actionFrom_NCBI_accessio_number.setText(_translate("MainWindow", "From NCBI accessio number "))
        self.actionBlank_entry.setText(_translate("MainWindow", "Blank entry"))
        self.actionTo_existing_entry.setText(_translate("MainWindow", "Nucleotide"))
        self.actionProtein.setText(_translate("MainWindow", "Protein"))

